[tool.poetry]
name = "innohassle-events"
version = "0.1.0"
description = ""
authors = ["Ruslan Bel'kov <ruslan.belckov@yandex.ru>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
aiofiles = "^24.0.0"
alembic = "^1.13.3"
asyncpg = "^0.30.0"
authlib = "^1.3.0"
colorlog = "^6.8.2"
cryptography = "^44.0.0"
fastapi = { extras = ["all"], version = "^0.115.6" }
fastapi-swagger = "^0.2.3"
gunicorn = "23.0.0"
icalendar = "^6.1.0"
pre-commit = "^4.0.1"
prometheus-fastapi-instrumentator = "^7.0.0"
pydantic = "^2.10.3"
python-multipart = "^0.0.19"
pytz = "^2024.2"
pyyaml = "^6.0.1"
ruff = "^0.8.3"
sqlalchemy = { extras = ["asyncpg"], version = "^2.0.30" }
uvicorn = "^0.34.0"

[tool.ruff]
line-length = 120
lint.ignore = [
    # wildcard imports are fine
    "F403",
    "F405",
    "PLR"
]
lint.extend-select = ["I", "UP", "PL"]
target-version = "py312"
