[tool.poetry]
name = "innohassle-events"
version = "0.1.0"
description = ""
authors = ["Ruslan Bel'kov <ruslan.belckov@yandex.ru>"]
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = "~3.12"
pydantic = "^2.7.1"
fastapi = { extras = ["all"], version = "^0.115.0" }
authlib = "^1.3.0"
cryptography = "^43.0.0"
icalendar = "^5.0.12"
aiofiles = "^23.2.1"
sqlalchemy = { extras = ["asyncpg"], version = "^2.0.30" }
asyncpg = "^0.29.0"
alembic = "^1.13.1"
pyyaml = "^6.0.1"
uvicorn = "^0.29.0"
colorlog = "^6.8.2"
prometheus-fastapi-instrumentator = "^7.0.0"

[tool.poetry.group.prod]
optional = true
[tool.poetry.group.prod.dependencies]
gunicorn = "22.0.0"

[tool.poetry.group.dev]
optional = true
[tool.poetry.group.dev.dependencies]
ruff = "^0.6.0"
pre-commit = "^3.7.0"

[tool.ruff]
line-length = 120
lint.ignore = [
    # wildcard imports are fine
    "F403",
    "F405",
]
