[tool.poetry]
name = "innohassle-events"
version = "0.1.0"
description = ""
authors = ["Ruslan Bel'kov <ruslan.belckov@yandex.ru>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
aiofiles = "^24.0.0"
alembic = "^1.14.0"
asyncpg = "^0.30.0"
authlib = "^1.3.0"
colorlog = "^6.9.0"
cryptography = "^43.0.3"
fastapi = { extras = ["all"], version = "^0.115.5" }
fastapi-swagger = "^0.2.5"
gunicorn = "23.0.0"
icalendar = "^6.0.1"
pre-commit = "^4.0.1"
prometheus-fastapi-instrumentator = "^7.0.0"
pydantic = "^2.7.1"
pyyaml = "^6.0.1"
ruff = "^0.7.3"
sqlalchemy = { extras = ["asyncpg"], version = "^2.0.36" }
uvicorn = "^0.32.0"

[tool.ruff]
line-length = 120
lint.ignore = [
    # wildcard imports are fine
    "F403",
    "F405",
    "PLR"
]
lint.extend-select = ["I", "UP", "PL"]
