[tool.poetry]
name = "innohassle-events"
version = "0.1.0"
description = ""
authors = ["Ruslan Bel'kov <ruslan.belckov@yandex.ru>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
aiofiles = "^24.0.0"
alembic = "^1.13.3"
asyncpg = "^0.29.0"
authlib = "^1.3.0"
colorlog = "^6.8.2"
cryptography = "^43.0.0"
fastapi = { extras = ["all"], version = "^0.115.0" }
fastapi-swagger = "^0.2.3"
gunicorn = "23.0.0"
icalendar = "^6.0.0"
pre-commit = "^3.7.0"
prometheus-fastapi-instrumentator = "^7.0.0"
pydantic = "^2.7.1"
pyyaml = "^6.0.1"
ruff = "^0.6.8"
sqlalchemy = { extras = ["asyncpg"], version = "^2.0.30" }
uvicorn = "^0.31.0"

[tool.ruff]
line-length = 120
lint.ignore = [
    # wildcard imports are fine
    "F403",
    "F405",
]
