# This file should be synced with:
# https://github.com/one-zero-eight/accounts/blob/main/inh_accounts_sdk.py

import datetime
import logging
from typing import Any

import httpx
from joserfc import jwt
from joserfc.errors import JoseError
from joserfc.jwk import RSAKey
from joserfc.jwt import JWTClaimsRegistry
from pydantic import BaseModel

from src.config import settings


class TelegramInfo(BaseModel):
    id: int
    first_name: str
    last_name: str | None = None
    username: str | None = None
    photo_url: str | None = None
    updated_at: datetime.datetime


class InnopolisInfo(BaseModel):
    email: str
    name: str | None = None
    is_student: bool = False
    is_staff: bool = False
    is_college: bool = False
    updated_at: datetime.datetime


class UserSchema(BaseModel):
    id: str
    innopolis_info: InnopolisInfo
    telegram_info: TelegramInfo | None = None
    innohassle_admin: bool = False


class UserTokenData(BaseModel):
    innohassle_id: str
    "InNoHassle Accounts ID"
    email: str
    "Innopolis email (@innopolis.university or @innopolis.ru)"
    telegram_id: int | None = None
    "User's Telegram ID connected to InNoHassle Accounts"


class InNoHassleAccounts:
    api_url: str
    api_jwt_token: str | None
    PUBLIC_KID = "public"
    key_set: dict[str, Any] | None = None

    def __init__(
        self,
        api_url: str = "https://api.innohassle.ru/accounts/v0",
        api_jwt_token: str | None = None,
    ):
        self.api_url = api_url
        self.api_jwt_token = api_jwt_token
        if self.api_jwt_token is None:
            logging.warning(
                "API JWT token is not set, you will not be able to call service endpoints that require authorization"
            )

    async def update_key_set(self):
        self.key_set = await self.get_key_set()

    def get_public_key(self) -> RSAKey:
        if self.key_set is None:
            raise RuntimeError("Key set should be initialized by `update_key_set`")
        key_data = next((key for key in self.key_set.get("keys", []) if key.get("kid") == self.PUBLIC_KID), None)
        if key_data is None:
            raise RuntimeError(f"Public key with kid={self.PUBLIC_KID!r} is missing in JWKS")
        return RSAKey.import_key(key_data)

    async def get_key_set(self) -> dict[str, Any]:
        async with httpx.AsyncClient() as client:
            response = await client.get(f"{self.api_url}/.well-known/jwks.json")
            response.raise_for_status()
            return response.json()

    def decode_token(self, token: str) -> UserTokenData | None:
        """
        Decode generated by InnoHassle Accounts user JWT token and return user data.
        If token is invalid, return None.
        """
        try:
            payload = self._get_jwt_claims(token)
            innohassle_id: str | None = payload.get("uid")
            email: str | None = payload.get("email")
            telegram_id: int | None = payload.get("telegram_id")
            if innohassle_id is None or email is None:
                raise JoseError("Missing required claims: uid/email")
            return UserTokenData(
                innohassle_id=innohassle_id,
                email=email,
                telegram_id=telegram_id,
            )
        except JoseError:
            logging.warning("Invalid token", exc_info=True)
            return None

    def get_authorized_client(self) -> httpx.AsyncClient:
        if not self.api_jwt_token:
            raise ValueError("API JWT token is not set")
        return httpx.AsyncClient(
            headers={"Authorization": f"Bearer {self.api_jwt_token}"},
            base_url=self.api_url,
        )

    def _get_jwt_claims(self, token: str) -> dict[str, Any]:
        pub_key = self.get_public_key()
        payload = jwt.decode(token, pub_key)
        claims = payload.claims
        JWTClaimsRegistry().validate(claims)
        return claims

    async def get_user(
        self,
        innohassle_id: str | None = None,
        email: str | None = None,
        telegram_id: int | None = None,
    ) -> UserSchema | None:
        """
        Get user by one of the provided identifiers.
        If multiple identifiers are provided, the first one that exists will be returned.
        """
        async with self.get_authorized_client() as client:
            urls = []
            if innohassle_id:
                urls.append(f"/users/by-id/{innohassle_id}")
            if email:
                urls.append(f"/users/by-innomail/{email}")
            if telegram_id:
                urls.append(f"/users/by-telegram-id/{telegram_id}")
            for url in urls:
                response = await client.get(url)
                try:
                    response.raise_for_status()
                    return UserSchema.model_validate(response.json())
                except httpx.HTTPStatusError as e:
                    if e.response.status_code == 404:
                        continue
                    raise e
            return None

    async def get_sport_token(self, innohassle_id: str) -> str:
        async with self.get_authorized_client() as client:
            response = await client.get("/tokens/generate-sport-token", params={"innohassle_id": innohassle_id})
            response.raise_for_status()
            return response.json()["access_token"]


if settings.accounts:
    inh_accounts: InNoHassleAccounts = InNoHassleAccounts(
        api_url=settings.accounts.api_url,
        api_jwt_token=settings.accounts.api_jwt_token.get_secret_value(),
    )
else:
    raise ImportError("InNoHassle Accounts is not configured in ./settings.yaml")
