"""init alembic

Revision ID: 0f714fc8defc
Revises:
Create Date: 2023-09-15 15:21:00.304533

"""
# ruff: noqa: E501
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0f714fc8defc"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "event_groups", sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False)
    )
    op.add_column(
        "event_groups", sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False)
    )
    op.add_column("events", sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False))
    op.add_column("events", sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "created_at")
    op.drop_column("events", "updated_at")
    op.drop_column("event_groups", "created_at")
    op.drop_column("event_groups", "updated_at")
    # ### end Alembic commands ###
