"""Add color for linked calendar

Revision ID: 2db361ce1d3d
Revises: a9f09ae0208d
Create Date: 2023-10-16 23:07:37.504254

"""
# ruff: noqa: E501
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2db361ce1d3d"
down_revision: Union[str, None] = "a9f09ae0208d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("linked_calendars", sa.Column("color", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("linked_calendars", "color")
    # ### end Alembic commands ###
