"""extract predefined data

Revision ID: a5e80abc2e66
Revises: 6f44af938cdf
Create Date: 2024-03-10 21:21:31.768371

"""

# ruff: noqa: E501
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a5e80abc2e66"
down_revision: Union[str, None] = "6f44af938cdf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_x_hidden_groups",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["event_groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "group_id"),
    )
    op.add_column("users", sa.Column("innohassle_id", sa.String(), nullable=True))
    op.create_unique_constraint(None, "users", ["innohassle_id"])
    op.drop_column("users", "status")
    op.drop_column("users_x_favorite_groups", "predefined")
    op.drop_column("users_x_favorite_groups", "hidden")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users_x_favorite_groups", sa.Column("hidden", sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column("users_x_favorite_groups", sa.Column("predefined", sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column("users", sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "innohassle_id")
    op.drop_table("users_x_hidden_groups")
    # ### end Alembic commands ###
