"""workshops hide

Revision ID: 2b7faa1a9627
Revises: 6b17213f3f14
Create Date: 2025-08-16 02:01:03.333292

"""

# ruff: noqa: E501
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2b7faa1a9627"
down_revision: str | None = "6b17213f3f14"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("workshops_hidden", sa.Boolean(), server_default=sa.text("false"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "workshops_hidden")
    # ### end Alembic commands ###
