"""user schedule access key

Revision ID: cba1388a6e8f
Revises: 8ff07476cbc4
Create Date: 2024-02-13 03:10:53.731890

"""

# ruff: noqa: E501
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cba1388a6e8f"
down_revision: str | None = "8ff07476cbc4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_schedule_keys",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("access_key", sa.String(), nullable=False),
        sa.Column("resource_path", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_schedule_keys_access_key"), "user_schedule_keys", ["access_key"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_schedule_keys_access_key"), table_name="user_schedule_keys")
    op.drop_table("user_schedule_keys")
    # ### end Alembic commands ###
