"""allow to hide room bookings

Revision ID: ae37e0d0ee10
Revises: 2b7faa1a9627
Create Date: 2026-02-12 00:14:27.332767

"""

# ruff: noqa: E501
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ae37e0d0ee10"
down_revision: str | None = "2b7faa1a9627"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("room_bookings_hidden", sa.Boolean(), server_default=sa.text("false"), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "room_bookings_hidden")
    # ### end Alembic commands ###
