"""moodle authtoken

Revision ID: 65da8a75e495
Revises: a5e80abc2e66
Create Date: 2024-09-13 16:39:20.527184

"""

# ruff: noqa: E501
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "65da8a75e495"
down_revision: Union[str, None] = "a5e80abc2e66"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("moodle_userid", sa.Integer(), nullable=True))
    op.add_column("users", sa.Column("moodle_calendar_authtoken", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "moodle_calendar_authtoken")
    op.drop_column("users", "moodle_userid")
    # ### end Alembic commands ###
