"""Add constraint for linked calendars

Revision ID: a9f09ae0208d
Revises: 85bf4b0af84d
Create Date: 2023-10-16 22:53:08.602036

"""
# ruff: noqa: E501
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "a9f09ae0208d"
down_revision: Union[str, None] = "85bf4b0af84d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("unique_user_id_alias", "linked_calendars", ["user_id", "alias"])
    op.drop_constraint("tags_alias_type_key", "tags", type_="unique")
    op.create_unique_constraint("unique_alias", "tags", ["alias", "type"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_alias", "tags", type_="unique")
    op.create_unique_constraint("tags_alias_type_key", "tags", ["alias", "type"])
    op.drop_constraint("unique_user_id_alias", "linked_calendars", type_="unique")
    # ### end Alembic commands ###
