name: Run pre-commit

on: [ push, pull_request ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: 👾 Check out repository
        uses: actions/checkout@v5
      - name: 📦 Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          activate-environment: true
      - name: 📦 Install the project
        run: uv sync
      - name: 🧪 Run pre-commit
        run: uv run pre-commit run --show-diff-on-failure --color=always --all-files --hook-stage manual
        env:
          RUFF_FORMAT: github
